name: build_with_test
  on: [pull_request]
    branch: [ master ]
  jobs: test
    run-on: ubuntu-latest
    steps: gradle setup and test
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
  1          distribution: temurin
            java-version: 11
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Execute Gradle build
          run: ./gradlew build

