name: GitHub Actions Demo
on: [pull_request]
jobs:
  Build-and-test-gradle-sample:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Start CI"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup java
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - run: echo "Start CI"
